const JOIN = 'JOIN';
const LEAVE = 'LEAVE';
const CHAT = 'CHAT';
const SYSTEM_CHAT = 'SYSTEM_CHAT';
const CREATE_ROOM = 'CREATE_ROOM';
const GET_ROOM_MEMBER_LIST = 'GET_ROOM_MEMBER_LIST';

export {
  JOIN,
  LEAVE,
  CHAT,
  SYSTEM_CHAT,
  CREATE_ROOM,
  GET_ROOM_MEMBER_LIST
}